### ISSUE TITLE
Error when running "serverless deploy"

### ISSUE THREAD

**Issue by brunofaim** [csuermann/virtual-smart-home#14]
Im getting all these errors when running "serverless deploy"

"Error
Cannot resolve serverless.yml: Variables resolution errored with:
  - Cannot resolve variable at "provider.environment.IS_PROD": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.MOMENTO_TOKEN": Value not found at "env" source,
  - Cannot resolve variable at "provider.environment.LOG_LEVEL": Value not found at "env" source,
  - Cannot resolve variable at "functions.backendApi.environment.STRIPE_API_KEY": Value not found at "env" source,
  - Cannot resolve variable at "functions.backendApi.environment.STRIPE_WEBHOOK_SECRET": Value not found at "env" source"
  
Can someone help me out with this. On the previous steps I also got

"npm WARN deprecated
npm WARN deprecated
npm WARN deprecated
npm WARN deprecated"

**Comment by csuermann** [comment]
The [readme](https://github.com/csuermann/virtual-smart-home/blob/sandbox/readme.md) has just been updated to include the missing environment variables.
