### ISSUE TITLE
any ideas for chasing down this bug?

### ISSUE THREAD

**Issue by jpadie** [csuermann/virtual-smart-home#19]
ERROR
provisioning failed! Try (re)-enabling the VSH Alexa skill!

amazon reports success but the node-flow reports failure.

amazon:
Success!
Your registration is now complete.

of course I have tried to look on the alexa dev console but there is no option to enable or disable a smart home skill that is not alexa-hosted.  I've double checked all the details and steps and the only variance is that the skill is named Rab vsh in lieu of my private vsh.  

pointers for debugging this would be gratefully received.  

I'm also looking to expand the thermometer model to include humidity.  this is accepted by alexa so i'm looking for pointers as to where to adapt the code to cater for these extensions (and others planned for the thermostat device model).  

thanks!

**Comment by jpadie** [comment]
resolved the blocking issue.

other issues have popped up but I will try squishing those before reposting.  help on the device model extensions still welcome.

**Comment by csuermann** [comment]
May I ask how you ended up resolving the issue? AFAIR the hint to re-enable the skill refers to the Alexa app rather than the server side.
