### ISSUE TITLE
Which is the specific license of this repository?

### ISSUE THREAD

**Issue by ismatim** [csuermann/virtual-smart-home#4]
I need to develop a feature for a product which is quite related with the functionality of this repository but, I am not sure if that is possible to do. Would you mind to specify? Thank you!

**Comment by csuermann** [comment]
Hi @ismatim,

The license is specified as "MIT" in the [package.json file](https://github.com/csuermann/virtual-smart-home/blob/a43154d450c7a35bc84e110baccbe9423e7863e4/package.json#L40)
