### ISSUE TITLE
[FEATURE-REQUEST] Running backend on own infrastructure

### ISSUE THREAD

**Issue by thohoj** [csuermann/virtual-smart-home#6]
It would be nice, if the backend could be run on my own endpoint. Currently I am running a simple custom skill (js, aws-sdk, express) in my own iobroker adapter...just because I can.

Is it possible to host the vsh backend in a similar manner?

**Comment by csuermann** [comment]
Hi @thohoj,
That is technically not possible at the moment, as Alexa's Smart Home Skill API requires AWS Lambda to function.
