### ISSUE TITLE
Cannot resolve serverless.yml: Variables resolution errored with

### ISSUE THREAD

**Issue by dumdiedum** [csuermann/virtual-smart-home#7]
After going through all points until severless deploy (20) there are still some variables which are not set, could you please help me which values are needed to fill those variables?

IS_PROD: ??? (false?)
LOG_LEVEL: ??? (warn?)
STRIPE_API_KEY: ???
STRIPE_WEBHOOK_SECRET: ???

**Comment by csuermann** [comment]
These variables got introduced when the "Pro" plan was rolled out. When running your own VSH backend deployment you don't really need them and can set them to nonsense-defaults, e.g.

IS_PROD: false
LOG_LEVEL: debug
STRIPE_API_KEY: abc
STRIPE_WEBHOOK_SECRET: xyz

The Stripe checkout to "Pro" would obviously not work but neither would it be needed.

**Comment by dumdiedum** [comment]
Thank you! Now deployment will start but throw this error:
The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource BackchannelLambdaFunction

Can you please help me with this?

**Comment by csuermann** [comment]
Hard to debug with so little context. Might have to do with the region you try to deploy to or with the version of the Serverless framework you use.

**Comment by dumdiedum** [comment]
Puh, it's working now. I'm new to AWS and severless and I had some issues with setup of environment since I'm using Windows. Thank you so much for your support!

**Comment by csuermann** [comment]
Glad to hear you succeeded! 🎉
