### ISSUE TITLE
Unresolved resource dependencies [vshClientPolicy2]

### ISSUE THREAD

**Issue by oziee** [csuermann/virtual-smart-home#8]
hi 

getting this error while `serverless deploy` is running

```
Error:
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [vshClientPolicy2] in the Resources block of the template
```

**Comment by csuermann** [comment]
You are probably trying to deploy to the wrong region. Try running `serverless deploy --region eu-west-1` or take a look at the [GitHub Action](https://github.com/csuermann/virtual-smart-home/blob/master/.github/workflows/sandbox.yml) for inspiration.

**Comment by oziee** [comment]
going to keep trying.. thanks

I did think if the IOT_ENDPOINT has xxxxxxx.ats.iot.us-east-1.amazonaws.com that setting the default region to `us-east-1` 

I will see what happens :)
