### ISSUE TITLE
provisioning failed! 

### ISSUE THREAD

**Issue by oziee** [csuermann/virtual-smart-home#9]
linked code to account, but the node red page changes to this
<img width="320" alt="Screen Shot 2022-10-06 at 9 01 41 pm" src="https://user-images.githubusercontent.com/1471841/194297008-ac8632a4-d752-4cc1-834d-a588558b786d.png">

<img width="1086" alt="Screen Shot 2022-10-06 at 9 26 14 pm" src="https://user-images.githubusercontent.com/1471841/194301206-5e1289c9-0907-47fa-93c7-5ed5d6a57555.png">

do I have to do something once I run serverless with adding to the pallet? or do I just use VSH from the distro?

**Comment by csuermann** [comment]
Is there anything suspicious in the AWS CloudWatch logs?

**Comment by oziee** [comment]
I see two lines that might be of use

- ERROR	PROVISIONING REQUEST for client with version 3.0.1

- ERROR	PROVISIONING FAILED: Thing Type 020358391743:virtual-smart-home-type not found.

I am using the latest copy in node-red and from this repo

**Comment by csuermann** [comment]
Did you create the thing type in the same region as specified in VSH_IOT_REGION (defaults to 'eu-west-1')?

**Comment by oziee** [comment]
well.. that's now a 64 million dollar question there.... hmmmm

is there a simple server less way to delete everything to be able to start again?

**Comment by oziee** [comment]
bugger.. still getting error

```
2022-10-07T11:40:27.368Z	5f90b211-885a-4c7b-902f-4c8887ab9ef6	ERROR	● /check_version with query: {
    "version": "3.0.1"
}

2022-10-07T11:40:27.387Z	5f90b211-885a-4c7b-902f-4c8887ab9ef6	ERROR	● RESPONSE: {
    "isAllowedVersion": true,
    "isLatestVersion": true,
    "updateHint": "",
    "allowedDeviceCount": 7
}

2022-10-07T11:41:15.369Z	9e92298d-859c-418b-9b21-c6e9c3ebaaf4	ERROR	ℹ PROVISIONING REQUEST for client with version 3.0.1

2022-10-07T11:41:15.749Z	9e92298d-859c-418b-9b21-c6e9c3ebaaf4	ERROR	✖ PROVISIONING FAILED: undefined

```

**Comment by oziee** [comment]
![Screen Shot 2022-10-07 at 10 17 15 pm](https://user-images.githubusercontent.com/1471841/194551942-a5e8365e-4972-4a7f-b034-4037669cd5cd.jpg)

**Comment by csuermann** [comment]
hmm, that "undefined" error message is not very helpful. One of the lines above [the error log statement](https://github.com/csuermann/virtual-smart-home/blob/master/backendApi.ts#L278) must be failing. You could try to extend the logging to figure out what's going on there.

**Comment by oziee** [comment]
fails here line 228
```
const { isBlocked } = await getUserRecord(profile.user_id)
```

removed all this from the try block
```
 const { isBlocked } = await getUserRecord(profile.user_id)

    if (isBlocked) {
      throw new Error(
        `found attribute 'isBlocked' for userId ${profile.user_id} / ${profile.email}`
      )
    }
```

and it now continues and no more errors

is removing the 'isBlocking' dangerous??

**Comment by oziee** [comment]
somewhere there is no user being created
```
2022-10-08T05:56:14.064Z	6b293b01-31ff-4993-909c-09bcad6223f1	ERROR	ℹ { TableName: 'VSH', Key: { PK: 'USER#amzn1.account.xxxxxxxxremovedxxxx', SK: 'TOKEN' } }

2022-10-08T05:56:14.301Z	6b293b01-31ff-4993-909c-09bcad6223f1	ERROR	ℹ no token record found

```

**Comment by oziee** [comment]
![Screen Shot 2022-10-08 at 4 12 55 pm](https://user-images.githubusercontent.com/1471841/194692262-42931b10-cda2-41c1-ac49-7427788a10c4.jpg)

**Comment by csuermann** [comment]
Ah, the node subtext is actually hinting at it: You must first enable **your** VSH skill in the Alexa app (Skills & Games > Your Skills > Dev > my private vsh). Once you've gone through the account linking process there, a [user record should get created](https://github.com/csuermann/virtual-smart-home/blob/master/handlers/acceptGrant.ts#L8).

**Comment by oziee** [comment]
after much much messing around I finally have it working..

thanks so much !

**Comment by csuermann** [comment]
Nice! What did the trick in the end?

**Comment by oziee** [comment]
reset the `Security Profile` - `Web Settings` - `Client Secret`

and kept trying to link the account until it finally worked :)

its not 100% yet.. its enabled, linked etc.. the DynamoDB table lists my devices **but** the Alexa app does not list or find them.. 

work in progress :)

**Comment by oziee** [comment]
seems that items are being added to the ash db table
<img width="719" alt="Screen Shot 2022-10-08 at 10 15 45 pm" src="https://user-images.githubusercontent.com/1471841/194707092-547abca4-4446-4372-a4c2-92d0ffef42cb.png">

but the skill is enabled
![IMG_0105](https://user-images.githubusercontent.com/1471841/194707116-e9c3c7d6-9165-48a8-91d0-40791e2f9194.jpg)

but there are still errors
```
2022-10-08T12:09:10.586Z	bccf6df8-9643-4773-a183-8ac1e86d26a3	ERROR	✖ proactivelyDiscoverDevices FAILED! Request failed with status code 403. Response body: {
    "header": {
        "namespace": "System",
        "name": "Exception",
        "messageId": "1e0a6bd1-c2ea-4a6c-8924-09b269c5df7b"
    },
    "payload": {
        "code": "SKILL_DISABLED_EXCEPTION",
        "description": "The user does not have a valid enablement for your skill."
    }
}
```

**Comment by csuermann** [comment]
I'm guessing this might still have to do with messed up regions...

Found this: https://amazon.developer.forums.answerhub.com/questions/204230/correct-regional-endpoint-to-avoid-skill-disabled.html
